#!/usr/bin/env sh
\n# taps
brew tap ethereum/ethereum
brew tap homebrew/versions
\n# packages
brew install autoconf
brew install boost
brew install cloc
brew install cloog
brew install cmatrix
brew install couchdb
brew install cowsay
brew install erlang
brew install ffmpeg
brew install flow
brew install fortune
brew install freetype
brew install gcc
brew install gdbm
brew install gettext
brew install git
brew install git-flow
brew install glew
brew install gmp
brew install gnutls
brew install gource
brew install icu4c
brew install isl
brew install jpeg
brew install lame
brew install libevent
brew install libmpc
brew install libpng
brew install libtasn1
brew install libtiff
brew install libtool
brew install libvo-aacenc
brew install mackup
brew install md5sha1sum
brew install mercurial
brew install mongodb
brew install mpfr
brew install nettle
brew install nspr
brew install openconnect
brew install openssl
brew install pcre
brew install pkg-config
brew install python
brew install python3
brew install rbenv
brew install rbenv-gem-rehash
brew install readline
brew install ruby-build
brew install sbt
brew install scala
brew install sdl2
brew install sdl2_image
brew install sloccount
brew install spidermonkey
brew install sqlite
brew install tidy-html5
brew install tmux
brew install unixodbc
brew install watchman
brew install webp
brew install wget
brew install wxmac
brew install x264
brew install xvid
brew install xz
brew install z
